### ISSUE TITLE
Question:  queryTable 的按钮怎么一直固定在最右边 不乱跑

### ISSUE THREAD

**Issue by 2401345934** [umijs/sula#105]
### Question
![image](https://user-images.githubusercontent.com/52618511/114883164-3be22b80-9e37-11eb-8d4d-e3d805b593d5.png)

### Description
queryTable 的按钮怎么一直固定在最右边 不乱跑

**Comment by xz8la8** [comment]
visibleFieldsCount 设置为true，https://docs.sula.vercel.app/template/query-form

**Comment by 2401345934** [comment]
> visibleFieldsCount设置为true，[https:](https://docs.sula.vercel.app/template/query-form) //docs.sula.vercel.app/template/query-form[](https://docs.sula.vercel.app/template/query-form)

 设置为 true 就没有了收起和展开    主要是想解决 不管展开和收起 查询和重置的按钮 永远固定在最右侧

**Comment by xz8la8** [comment]
https://docs.sula.vercel.app/template/query-form

你看下这个例子，不管是1、2、4都是在最右侧
