### ISSUE TITLE
Bug: 为 table 的 field 添加容器会报错

### ISSUE THREAD

**Issue by Codennnn** [umijs/sula#106]
### Versions

- sula: 1.2.0-beta.60
- umi-plugin-sula: 1.0.0-beta.2
- OS: Windows10
- Browser: Chrome 90.0.4430.212

### Steps to reproduce
为 table 的 field 添加容器，配置如下：
```json
{
  "layout": "vertical",
  "rowKey": "id",
  "columns": [
    {
      "key": "id",
      "title": "ID"
    }
  ],
  "fields": [
    {
      "container": {  "type": "div" },
      "fields": [
        {
          "name": "name",
          "label": "标题",
          "field": "input"
        }
      ]
    }
  ]
}
```

### What is actually happening?
![image](https://user-images.githubusercontent.com/47730755/118118073-0113e900-b41f-11eb-8aa1-e175288f8088.png)

**Comment by xz8la8** [comment]
fields  => Field[]，Field 不支持 container

**Comment by Codennnn** [comment]
> fields => Field[]，Field 不支持 container

请问要怎么修改呢，我想实现的是像 sula-builder 里面 field 外套一层 catcher 组件。

**Comment by Codennnn** [comment]
为什么表单的 field 可以添加嵌套容器，而表格的用同样的方式却不行呢？
