### ISSUE TITLE
Question: 如何处理 request 插件的 URL 以动态添加 ID ？

### ISSUE THREAD

**Issue by Codennnn** [umijs/sula#110]
### Question

如何处理 request 插件的 URL 以动态添加 ID ？

### Description

目标 URL 需要拼接 ID 以请求特定数据（如下图红框所示）

![image](https://user-images.githubusercontent.com/47730755/120260256-1d8d9d80-c2c8-11eb-98d9-dc7c1778b7ed.png)

目前我了解到的方法有两个：

1. 使用模板字符串，但是 ctx 只能访问到 form 实例、mode、param，能不能也将 history 扩写进去呢？

2. 使用 bizRequestAdapter 去修改请求

不知道还有什么好的解决方法呢？

**Comment by xz8la8** [comment]
这种参数一般都是url带过来的吧，用`/abc/${params.id}` 就行。

**Comment by Codennnn** [comment]
> 这种参数一般都是url带过来的吧，用`/abc/${params.id}` 就行。

如果是使用 json 配置的话，如何获取到 params.id 呢？
