### ISSUE TITLE
Bug:运行项目后会报 ./src/.umi/SulaConfigProviderWrapper.js 里面的 getLocale 函数导出错误警告

### ISSUE THREAD

**Issue by zeweilin1993** [umijs/sula#120]
### Versions

- sula:^1.2.0-beta.68
- umi-plugin-sula:^1.0.0-beta.2
- OS:
- Browser:Chrome

**Comment by xz8la8** [comment]
麻烦把报错截图贴下呗

**Comment by zeweilin1993** [comment]
![image](https://user-images.githubusercontent.com/39040618/131469771-f42c6467-30e9-48aa-9659-d4ef80ec9616.png)

**Comment by zeweilin1993** [comment]
![image](https://user-images.githubusercontent.com/39040618/131469845-dd846f1b-b996-4b8d-809e-8afda069948b.png)

**Comment by xz8la8** [comment]
贴一下你的 .umirc.js 或者 config/config.js

**Comment by zeweilin1993** [comment]
![image](https://user-images.githubusercontent.com/39040618/131470662-52ee1ce6-b982-46a7-ac77-04393fdb1c1f.png)

**Comment by zeweilin1993** [comment]
![image](https://user-images.githubusercontent.com/39040618/131472950-cef302fb-2568-42ed-b08d-b37d5a085c66.png)

**Comment by xz8la8** [comment]
参考下：https://docs.sula.vercel.app/docs/globalization
export default {
  // 开启 umi-plugin-locale
  locale: {}
}

**Comment by zeweilin1993** [comment]
ok，感谢
