### ISSUE TITLE
使用ant design pro 模板，样式丢失？

### ISSUE THREAD

**Issue by yichangle** [umijs/sula#19]
先创建ant design pro 模板，完全复制文档中的代码，依据文档中的说明安装插件和依赖，结果样式显示有问题。
最后一行return <CreateForm {...config} /> vscode提示如下错误：
(alias) const CreateForm: typeof _CreateForm
import CreateForm
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<CreateFormProps>): CreateForm', gave the following error.
    不能将类型“{ fields: { name: string; label: string; field: string; }[]; submit: { url: string; method: string; }; }”分配给类型“Pick<Readonly<CreateFormProps> & Readonly<{ children?: ReactNode; }>, "name" | "form" | "slot" | "style" | "title" | "children" | ... 283 more ... | "ctxGetter">”。
      The types of 'submit.method' are incompatible between these types.
        不能将类型“string”分配给类型“"POST" | "head" | "link" | "get" | "GET" | "delete" | "DELETE" | "HEAD" | "options" | "OPTIONS" | "post" | "put" | "PUT" | "patch" | "PATCH" | "LINK" | "unlink" | "UNLINK" | undefined”。
  Overload 2 of 2, '(props: CreateFormProps, context?: any): CreateForm', gave the following error.
    不能将类型“{ fields: { name: string; label: string; field: string; }[]; submit: { url: string; method: string; }; }”分配给类型“Pick<Readonly<CreateFormProps> & Readonly<{ children?: ReactNode; }>, "name" | "form" | "slot" | "style" | "title" | "children" | ... 283 more ... | "ctxGetter">”。
      属性“submit”的类型不兼容。
        不能将类型“{ url: string; method: string; }”分配给类型“RequestConfig”。ts(2769)
速览问题 (Alt+F8)
没有可用的快速修复

**Comment by xz8la8** [comment]
可以使用umi的antd插件引入样式，或者在global.js or global.less 引入antd样式
