### ISSUE TITLE
Feature: 能将createTable里的分页器用自定义的方式换成其他自定义的组件吗

### ISSUE THREAD

**Issue by chenhaina** [umijs/sula#29]
### Description
将createTable里的分页器

![image](https://user-images.githubusercontent.com/20574704/86441229-76faee80-bd3e-11ea-803f-15e1f03f211a.png)
换成自定义的分页器（因为后端不肯返回total）
![image](https://user-images.githubusercontent.com/20574704/86441357-aa3d7d80-bd3e-11ea-82cf-541dffb3c9e2.png)

**Comment by xz8la8** [comment]
有点矛盾哈，如果没有total，怎么知道还有下一页呢，最好和后端协商下，他们做分页肯定是知道总数的哈

**Comment by Rock2018** [comment]
> 有点矛盾哈，如果没有total，怎么知道还有下一页呢，最好和后端协商下，他们做分页肯定是知道总数的哈

   其实是这样的哈，因为某些场景下， 后端考虑到系统性能等一些原因， 所以没有在业务取舍上 ，去掉了总数。 而是只给上一页下一页这种方式。 比如后端通常用mysql 做数据库， 而mysql 的count 性能在数据量过千万的时候是极其差的

**Comment by chenhaina** [comment]
需求都没有实现，考虑性能？？？

**Comment by Rock2018** [comment]
> 需求都没有实现，考虑性能？？？

emmmmm 怎么解释， 需求跟性能 有的时候是可以做取舍的， 如果需求在业务里不是刚需，而性能问题比较突出的情况下，有可能会放弃需求，选择性能， 这个问题。 我们看看能不能做一个上一页，下一页的组件来解决， 就不纠结了。  感谢官方。

**Comment by xz8la8** [comment]
嗯嗯，建议还是跟后端再沟通下哈，即使数据量再大，这也不能算极特殊场景，后端肯定有解决办法的，否则这个需求前端做起来坑也会不少，用户使用也会比较懵。
