### ISSUE TITLE
请教两个问题：1、业务开发经常碰到表单控件之间存在联动关系，如果采用json存储在后端的方式，控件之间的联动逻辑如何与后端存储的json关联？2、通常业务场景会经常碰到列表进入详情界面需要保存分页和查询条件，然后详情界面返回列表界面查询以及分页还保留之前的状态，这个我看模版里面木有相应的api可以实现？

### ISSUE THREAD

**Issue by wo-de-ping-er** [umijs/sula#33]

**Comment by xz8la8** [comment]
1. 可以进行表单组件间的关联配置哈：参考[表单关联](https://sula.now.sh/#/advanced/form-advanced#dependency)
2. table提供了getPaging()方法可以拿到当前的分页信息（这里记为pagingResult）包括pagination、filters、sorter，同时提供了setPaging，将pagingResult作为参数传入setPaging即可。

**Comment by wo-de-ping-er** [comment]
> 1. 可以进行表单组件间的关联配置哈：参考[表单关联](https://sula.now.sh/#/advanced/form-advanced#dependency)
> 2. table提供了getPaging()方法可以拿到当前的分页信息（这里记为pagingResult）包括pagination、filters、sorter，同时提供了setPaging，将pagingResult作为参数传入setPaging即可。

表格跳转到详情界面分页信息需要暂存，这边的数据暂存存储在前端，这部分数据暂存是需要我们编码做暂存  对吧？

**Comment by xz8la8** [comment]
目前是的哈
