### ISSUE TITLE
Question:如何统一在submit、remoteValues、remoteDataSource的请求里加上请求头

### ISSUE THREAD

**Issue by chenhaina** [umijs/sula#34]
### Question
 QueryTable里面的一些属性，比如说ModalForm里的submit、remoteValues和QueryTable里congfig的remoteDataSource都会发起请求，如何在请求发送前拦截统一加上请求头？
![image](https://user-images.githubusercontent.com/20574704/86867086-c8232d80-c104-11ea-9824-ec7ac3829a07.png)

**Comment by chenhaina** [comment]
已解决。感谢

**Comment by xz8la8** [comment]
参考：https://sula.now.sh/#/sula-api/request?anchor=bizrequestadapter
