### ISSUE TITLE
Question: 请问一下， sula 是否支持我自己写一个上一页 下一页， 不带total 这种分页

### ISSUE THREAD

**Issue by Rock2018** [umijs/sula#36]
### Question
 请问一下， sula 是否支持我自己写一个上一页 下一页， 不带total 这种分页
### Description
业务场景： 由于后端大部份 是通过mysql 来存储， 有的时候考虑到mysql select count(*) 的性能问题， 我们是不给前端返回分页总数的， 但是sula 目前的分页组件，好像需要返回总数才可以使用， 所以请问一下， 我们如何自定义这种分页组件，给官方提pr ?

**Comment by Augustzyh** [comment]
我也觉得这些也是基础功能，我还以为是完全继承antd的pros，配置半天才去官网看了没有

**Comment by xz8la8** [comment]
如果不给total，要补充很多细节，比如什么时候有上一页，什么时候有下一页，需要在返回数据里给出，请详细描述下，开新帖讨论。
