### ISSUE TITLE
Bug: request插件期望可以完全自定义

### ISSUE THREAD

**Issue by xiexingen** [umijs/sula#55]
request插件期望可以完全自定义
### Description
1.一个表单配置了N个下拉选择框 都是远程数据，其中可能有大部分是重复的数据源
2.保存的axios想使用系统里面自定义好的axios实例(已经定义了拦截器、响应器不想再在sula中再写一次)
### Solution
是否可以提供一个扩展 传递一个axios实例，完成替换掉sula的axios；
这样重复的字典数据请求，授权的拦截、响应的拦截 在系统层面可以保存一致

**Comment by xz8la8** [comment]
这个问题很赞，是否可以在sula扩展一个能力去缓存数据呢，可以给出更具体的实施建议。个人觉得替换axios我觉得是另外一个独立问题

**Comment by xiexingen** [comment]
1.缓存的我也没想到有什么好的办法
2.替换axios的问题好不好扩展
  2.1 可以系统层面统一
  2.2 有些人用的不是axios，比如 umi-request、甚至fetch啥的

**Comment by xz8la8** [comment]
已支持自定义request覆盖
