### ISSUE TITLE
Bug: builder配置久了频繁报错

### ISSUE THREAD

**Issue by Augustzyh** [umijs/sula#60]
![1](https://user-images.githubusercontent.com/38031220/93451364-acf54b00-f909-11ea-85d6-7b6aefcce497.jpg)
builder配置老是报上面的错误然后页面就空白了
![2](https://user-images.githubusercontent.com/38031220/93451403-b7174980-f909-11ea-9655-24e292f6dfa9.jpg)
需要手动把localstorage清理掉刷新才会重新显示，这样之前配置的东西就都没了

**Comment by xz8la8** [comment]
目前还是尝鲜版，主要是让大家了解下能力，没有经过太多内部验证，更加稳定的版本请等待我们的开源版本哈~
