### ISSUE TITLE
Bug: confirm是英文的，ConfigProvider已经设置中文了

### ISSUE THREAD

**Issue by shixintian** [umijs/sula#62]
![image](https://user-images.githubusercontent.com/23206181/94666883-9eaf2200-0340-11eb-99bb-9c9463ebea06.png)
confirm是英文的，ConfigProvider已经设置中文了。这个是sula-real的页面

**Comment by xz8la8** [comment]
ConfigProvider是管理sula国际化的，你需要配置antd的国际化
