### ISSUE TITLE
Bug: bizRequestAdapter 插件设置 post method body为空

### ISSUE THREAD

**Issue by chinacoolboyzz** [umijs/sula#66]
```javascript
import { request } from 'sula';
request.use({
  bizRequestAdapter(requestConfig) {
    requestConfig.method = 'POST';
    return requestConfig;
  },
});
```
request 的 bizRequestAdapter里设置method无效，还是已默认的 get 方式挂载参数到url上 body 为空

**Comment by slq521** [comment]
初始设定了get请求，request会处理成params来挂载参数；你通过bizRequestAdapter更改为post，请求方式变了，但是请求参数没有变（还是params）。你可以更改一下请求参数，类似于 requestConfig.data = requestConfig.params。
