### ISSUE TITLE
Bug: upload组件无法上传文件

### ISSUE THREAD

**Issue by jdh** [umijs/sula#70]
### Versions

https://sula.now.sh/

### Steps to reproduce
![image](https://user-images.githubusercontent.com/110164/97719034-97c32d00-1b01-11eb-98d2-13a60fe6f9c9.png)
请求头改为
```
"headers": {
       "content-type": "application/x-www-form-urlencoded"
 },
```
经过transformConfig处理侯formData就丢了

### What is Expected?
能上传文件

**Comment by slq521** [comment]
已修复 #71
