### ISSUE TITLE
Feature: QueryTable 支持自定义查询按钮

### ISSUE THREAD

**Issue by jiyingzhi** [umijs/sula#86]
QueryTable 支持给查询和重置按钮传递属性，控制是否显示，提供查询和重置事件

**Comment by Hencky** [comment]
请详细描述下场景，不太明白需求

**Comment by yingzhiji** [comment]
比如在特定条件下让查询按钮 disabled，点击查询按钮的时候执行函数，有时候只有一个搜索条件想去掉重置按钮

**Comment by yingzhiji** [comment]
补充需求场景：点击查询按钮，设置一个3s的定时，然后disabled查询按钮，3s过后恢复，后端服务器有限制，不能请求太频繁

**Comment by Timo1216** [comment]
mark

**Comment by SturdyCat** [comment]
@Hencky 期望在按钮内部可以和筛选条件产生联动，目前自定义按钮只能获取表格的数据，无法获取到当前的筛选情况进行一些处理

**Comment by xz8la8** [comment]
> @Hencky 期望在按钮内部可以和筛选条件产生联动，目前自定义按钮只能获取表格的数据，无法获取到当前的筛选情况进行一些处理

这个我稍晚看下，把过滤条件的form实例放到table里

**Comment by xz8la8** [comment]
需求不明确，暂时关闭
