### ISSUE TITLE
Feature: 有升级umi3.0的计划吗？

### ISSUE THREAD

**Issue by JtCheung** [umijs/sula#91]

**Comment by xz8la8** [comment]
现在就是支持的umi3.0

**Comment by JtCheung** [comment]
umi3.0安装umi-plugin-sula，配置
``` umi.rc
sula: {
  locale: {
      default: 'zh-CN',
      baseNavigator: false,
  }
}
```
使用buttonLink不生效，设置中文也不生效

**Comment by Hencky** [comment]
参考下：[https://github.com/umijs/sula-real/blob/master/src/layout/index.js](https://github.com/umijs/sula-real/blob/master/src/layout/index.js) ，设置ConfigProvider，如果不能解决，show me the code.

**Comment by xz8la8** [comment]
本周会把 SulaConfigProvider 的配置放到 umi-plugin-sula插件中，sula-real也中也会屏蔽掉SulaConfigProvider的配置，再发布。

**Comment by JtCheung** [comment]
> 本周会把 SulaConfigProvider 的配置放到 umi-plugin-sula插件中，sula-real也中也会屏蔽掉SulaConfigProvider的配置，再发布。

好像type为route的渲染组件在3.0也有点问题
![image](https://user-images.githubusercontent.com/27285135/106225703-ac0de780-6220-11eb-9a7a-8a6b3e5f9010.png)

**Comment by JtCheung** [comment]
> 参考下：https://github.com/umijs/sula-real/blob/master/src/layout/index.js ，设置ConfigProvider，如果不能解决，show me the code.

这样设置Query-Table有中文的，但是Search-Table这类新的没有。

**Comment by xz8la8** [comment]
该问题标题和讨论内容不符，如有问题请新开帖
