### ISSUE TITLE
setp-Form  中间步骤跳转的时候可以调用接口吗？ 请问各位大佬

### ISSUE THREAD

**Issue by 2401345934** [umijs/sula#97]
有没有方法支持我 在第一步 跳转到第二步的时候 调用接口呢     或者
   我重写actionRender 按钮 的时候 有没有哪个属性控制 目前在第几步    
  因为 目前我看到 官网的  setp-Form 是只有在最后一步才可以调接口  
 目前遇到的诉求是  比如是在第一步  到 第二步的时候 调用一个接口

**Comment by 2401345934** [comment]
@sorrycc

**Comment by xz8la8** [comment]
#99
