### ISSUE TITLE
Feature: pro的request和sula的request能融合成一个嘛

### ISSUE THREAD

**Issue by poal222** [umijs/sula#98]
### Description
当前团队pc的前端均使用pro+pro-component编写。
最近开始做前端的低代码功能。测试了一下阿里系和umi系的一些渲染组件，觉得使用sula成本最低。
但是sula的网络请求是使用的自己封装的，和pro的基于umi-request的不一样。
当前pro的请求组件做了大量的异常处理及认证方面的内容。
希望能给个sula使用pro的请求组件的demo。方便团队无缝迁移。

**Comment by rodchen-king** [comment]
我写了两套，pro的一套，sula的一套。因为调用的request不同。

**Comment by xz8la8** [comment]
sula1.2.0-beta2.0
