### ISSUE TITLE
RFC - StepForm 支持暂存功能

### ISSUE THREAD

**Issue by xz8la8** [umijs/sula#99]
StepForm 新增 **save** 属性（配置方式同 submit ），支持单步保存接口配置。当检测到save配置时，StepForm将有如下变化。

1. 步骤条的每一个步骤可点击切换。
2. 新建和编辑模式增加暂存按钮，暂存按钮提交参数是所有步骤的表单值（并非当前步骤），且收集参数不会触发校验

暂存按钮提交表单走save配置，提交按钮提交表单走submit配置。

**Comment by 2401345934** [comment]
官网 什么时候回更新下文档 呢 请问 @xz8la8

**Comment by xz8la8** [comment]
> 官网 什么时候回更新下文档 呢 请问 @xz8la8

1.2.0-beta.30  StepForm 支持单步保存（暂存）功能
文档：https://docs.sula.now.sh/template/step-form#StepForm-demo-1

**Comment by xz8la8** [comment]
已支持，有问题再开
